"""initial

Revision ID: a5f613b1a632
Revises: 986ffd124037
Create Date: 2026-04-15 14:15:19.839903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a5f613b1a632'
down_revision: Union[str, None] = '986ffd124037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###