"""add_products_fields_hsn_review

Revision ID: 95de41c35ba8
Revises: a5f613b1a632
Create Date: 2026-04-15 14:32:31.496548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '95de41c35ba8'
down_revision: Union[str, None] = 'a5f613b1a632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hsn_codes',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('chapter', sa.String(length=2), nullable=True),
    sa.Column('section', sa.String(length=5), nullable=True),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_hsn_codes_chapter'), 'hsn_codes', ['chapter'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('brand', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('subcategory', sa.String(length=200), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('mrp', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('selling_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('weight_grams', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('volume_ml', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('hsn_code', sa.String(length=8), nullable=True),
    sa.Column('ondc_category', sa.String(length=100), nullable=True),
    sa.Column('ondc_subcategory', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('confidence_overall', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence_overall BETWEEN 0 AND 1', name='ck_product_confidence_range'),
    sa.ForeignKeyConstraint(['hsn_code'], ['hsn_codes.code'], ),
    sa.ForeignKeyConstraint(['job_id'], ['ingestion_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=False)
    op.create_index(op.f('ix_products_created_at'), 'products', ['created_at'], unique=False)
    op.create_index(op.f('ix_products_hsn_code'), 'products', ['hsn_code'], unique=False)
    op.create_index(op.f('ix_products_job_id'), 'products', ['job_id'], unique=False)
    op.create_table('product_fields',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('normalized_value', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name='ck_field_confidence_range'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_fields_product_id'), 'product_fields', ['product_id'], unique=False)
    op.create_table('review_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('extracted_value', sa.Text(), nullable=True),
    sa.Column('suggested_value', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending','accepted','rejected')", name='ck_review_status'),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name='ck_review_confidence_range'),
    sa.ForeignKeyConstraint(['job_id'], ['ingestion_jobs.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_items_created_at'), 'review_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_review_items_job_id'), 'review_items', ['job_id'], unique=False)
    op.create_index(op.f('ix_review_items_product_id'), 'review_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_review_items_status'), 'review_items', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_items_status'), table_name='review_items')
    op.drop_index(op.f('ix_review_items_product_id'), table_name='review_items')
    op.drop_index(op.f('ix_review_items_job_id'), table_name='review_items')
    op.drop_index(op.f('ix_review_items_created_at'), table_name='review_items')
    op.drop_table('review_items')
    op.drop_index(op.f('ix_product_fields_product_id'), table_name='product_fields')
    op.drop_table('product_fields')
    op.drop_index(op.f('ix_products_job_id'), table_name='products')
    op.drop_index(op.f('ix_products_hsn_code'), table_name='products')
    op.drop_index(op.f('ix_products_created_at'), table_name='products')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_hsn_codes_chapter'), table_name='hsn_codes')
    op.drop_table('hsn_codes')
    # ### end Alembic commands ###